import { Inter } from 'next/font/google';
import './globals.css';
import { SideNavbar } from './components/SideNav';
import { NavBarComp } from './components/Navbar';
import { InitConection } from './components/Init';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<head>
				<script
					async
					src='https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.js'
				></script>
			</head>
			<body className={inter.className}>
				<InitConection />
				<div className='flex h-screen'>
					<SideNavbar />
					<div className='ml-64 w-full'>
						<NavBarComp />
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
